### ISSUE TITLE
How do I get passed the "confirmation email sent" in development?

### ISSUE THREAD

**Issue by gmcamposano** [kobaltz/action_auth#2]
Hi, Sorry for this newbie question, maybe this is something I need to know but I am new to this. I can't figure what should i do to verify emails, or reset email when working in development / production. Can you help me out?

**Comment by kobaltz** [comment]
You can check the logs, use a gem like letter_opener, or a mail service locally like mailcrab. Here's an episode on Mailhog, but now-a-days, I prefer Mailcrab since they have a native arm64 build. https://www.driftingruby.com/episodes/local-mail-delivery
