### ISSUE TITLE
Share login through multiple subdomains

### ISSUE THREAD

**Issue by beetlegius-jt** [kobaltz/action_auth#9]
Hello :) I noticed the gem doesn't allow me to login through multiple subdomains. After a quick research, I found the signed cookie options does not include `domain: :all` and I couldn't find a way to configure it from outside (like a specific configuration or default options for cookies).

https://github.com/kobaltz/action_auth/blob/00d9a8ebf15bdaefaad53671e0be0f186fc9e5c2/app/controllers/action_auth/sessions_controller.rb#L22

Changing the local gem code to something like this works fine:
```ruby
cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true, domain: :all }
```

Thanks!

**Comment by kobaltz** [comment]
Release v1.7.1 has been pushed to address this. It is disabled by default but you can enable it with `config.insert_cookie_domain = true` in your ActionAuth config.
